rabbitmq:
  queue: "oms.order.created"
  consumer_tag: "consumer-svc"
  auto_ack: false
  exclusive: false
  no_local: false
  no_wait: false

grpc:
  order_service_addr: "order-svc:9001"
  timeout_seconds: 30
