services:
  order-pg:
    image: postgres
    environment:
      POSTGRES_DB: ${ORDER_PG_DB}
      POSTGRES_USER: ${ORDER_PG_USER}
      POSTGRES_PASSWORD: ${ORDER_PG_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - order-pgdata:/var/lib/postgresql
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  order-pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=${ORDER_PG_HOST}
      - DB_PORT=${ORDER_PG_PORT}
      - DB_USER=${ORDER_PG_USER}
      - DB_PASSWORD=${ORDER_PG_PASSWORD}
      - DB_NAME=${ORDER_PG_DB}
      - PGBOUNCER_AUTH_TYPE=plain
      - PGBOUNCER_IDLE_TRANSACTION_TIMEOUT=60
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MIN_POOL_SIZE=5
      - PGBOUNCER_SERVER_RESET_QUERY_ALWAYS=0
      - PGBOUNCER_SERVER_LIFETIME=3600
      - PGBOUNCER_SERVER_IDLE_TIMEOUT=60
      - PGBOUNCER_MAX_DB_CONNECTIONS=50
      - PGBOUNCER_MAX_CLIENT_CONN=10000
      - PGBOUNCER_RESERVE_POOL_SIZE=5
      - PGBOUNCER_MIN_POOL_SIZE=2
      - PGBOUNCER_DEFAULT_POOL_SIZE=16
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
    volumes:
      - ./configs/pgbouncer/userlist-order.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      order-pg:
        condition: service_healthy
    ports:
      - 5432:5432

  order-svc:
    build:
      context: ./order-svc
      dockerfile: Dockerfile
    ports:
      - 3001:3001
      - 9001:9001
    volumes:
      - .env:/app/.env
      - ./configs/order-svc/local.yml:/etc/order-svc/config.yml
    depends_on:
      - order-pgbouncer
      - rabbitmq
      - jaeger

  audit-pg:
    image: postgres
    environment:
      POSTGRES_DB: ${AUDIT_PG_DB}
      POSTGRES_USER: ${AUDIT_PG_USER}
      POSTGRES_PASSWORD: ${AUDIT_PG_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    volumes:
      - audit-pgdata:/var/lib/postgresql
      - ./configs/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  audit-pgbouncer:
    image: edoburu/pgbouncer:latest
    environment:
      - DB_HOST=${AUDIT_PG_HOST}
      - DB_PORT=${AUDIT_PG_PORT}
      - DB_USER=${AUDIT_PG_USER}
      - DB_PASSWORD=${AUDIT_PG_PASSWORD}
      - DB_NAME=${AUDIT_PG_DB}
      - PGBOUNCER_AUTH_TYPE=plain
      - PGBOUNCER_IDLE_TRANSACTION_TIMEOUT=60
      - PGBOUNCER_POOL_MODE=transaction
      - PGBOUNCER_MIN_POOL_SIZE=5
      - PGBOUNCER_SERVER_RESET_QUERY_ALWAYS=0
      - PGBOUNCER_SERVER_LIFETIME=3600
      - PGBOUNCER_SERVER_IDLE_TIMEOUT=60
      - PGBOUNCER_MAX_DB_CONNECTIONS=50
      - PGBOUNCER_MAX_CLIENT_CONN=10000
      - PGBOUNCER_RESERVE_POOL_SIZE=5
      - PGBOUNCER_MIN_POOL_SIZE=2
      - PGBOUNCER_DEFAULT_POOL_SIZE=16
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
    volumes:
      - ./configs/pgbouncer/userlist-audit.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      audit-pg:
        condition: service_healthy
    ports:
      - 5433:5432

  order-audit-consumer-svc:
    build:
      context: .
      dockerfile: ./order-audit-consumer-svc/Dockerfile
    volumes:
      - .env:/app/.env
      - ./configs/order-audit-consumer-svc/local.yml:/etc/consumer-svc/config.yml
    depends_on:
      - order-svc
      - rabbitmq
      - jaeger
      - audit-pgbouncer

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

volumes:
  order-pgdata:
  audit-pgdata:
  rabbitmq_data:
